### ISSUE TITLE
Github Oauth not working

### ISSUE THREAD

**Issue by TudorZgimbau** [voracious/octo#239]
Although the app can connect to GitHub, it fails to log the user in.
Browser: Safari
Other details: In the octo.app local storage, the "providers" array in the "user" key is empty.

**Comment by voracious** [comment]
I believe this problem is related to https://github.com/firebase/firebase-js-sdk/issues/6716#issuecomment-1320593233. Based on [a link from that comment](https://firebase.google.com/docs/auth/web/redirect-best-practices#mitigation_3_proxy_auth_requests_to_firebaseappcom), I did the following in an attempt to fix the issue.

- Proxy all requests for `https://octo.app/__/auth` to `https://api.octo.app/__/auth`
- Update all OAuth providers to use the new `https://octo.app/__/auth` hook
- Update the `octo.app` deployment to use `octo.app` as the auth domain instead of `api.octo.app`

**Comment by TudorZgimbau** [comment]
The issue seems to be resolved. Thank you very much for helping, feel free to close this if appropriate.
